- ewcmd.py
- ewfarm.py
- ewkingpin.py
- ewsmelting.py
- ewwep.py
- updated !balancecosmetic, should work now
- slimecorp executives can banish and pardon people
- fixed !whatcanimake not showing results for some recipes
- pitchfork also affects metallic crops now
> quick fixes and pitchfork buff

- page_player.py
Updating python3 requires replacing the cgi module with html.
> Replace cgi module with html

- client.py
- ewapt.py
- ewcmd.py
- ewhunting.py
- ewleaderboard.py
- ewslimetwitter.py
- ewwep.py
- small change to taunting: it has decreased effectiveness the lower the taunter's level is compared to the person taunted
- disabled shambler leaderboard, enabled zines leaderboard
- made slime leaderboard show top 5 slimiest?? :O
> tweet from dms, re-enabled combat commands

- ewfood.py
- ewleaderboard.py
- ewmap.py
- ewquadrants.py
- ewutils.py
- json/poi.json
> added missing poi connections, fixed capping bonuses

- ewcfg.py
- ewdistrict.py
- ewfish.py
- ewhunting.py
- ewjuviecmd.py
- json/poi.json
- removed 'JUVIE' from captcha list, as it conflicted with enemy aliases
- enemy str_kill formatting for civillian weapons
- there should be no way to get kicked into streets now
- fixed not being able to leave the underworld subway station
Legal limit:
- fixed safe juvies being killable by explosions
- fish caught under lega limit don't give slime on !barter
- can't get poudrin frenzy events, can't increase poudrin chances
> fixed some bugs, made legal limit limit more

- ew.py
- ewcasino.py
- ewitem.py
> changed how gellphones are looked for

- client.py
- ewcfg.py
- ewrace.py
I added the shambler race and their abilities. Feel free to review and PLEASE tell me if I messed something up!
~Glimmer
> shambler race addition

- ewcfg.py
- ewhunting.py
- ewmap.py
Changes:
- Added hunting announcements for Slimecorp
- Added special time announcements for Slimecorp
All tested and functions properly, I decided to use #slimecorp-comms instead of #the-breakroom in order to give the Slimecorp Security Forces a bit of a leg up.
> Gave Slimecorp Hunting & Time announcements

- ewhunting.py
> fixed scouting bug

- ewtransport.py
Trains should now stay on separate lines from their twins. The green line is now perpetually late. All other lines receive negligible delays.
> Trains now hold intended distance

- ewcfg.py
- ewfish.py
- ewtransport.py
-increased subway speed to 10 seconds/stop
-increased embark/disembark speed to 2 seconds
-increased chance to reel ocean trash when reeling an item
> Faster subways and more ocean trash

- ew.py
- ewcfg.py
- ewdistrict.py
- ewfish.py
- ewhunting.py
- ewjuviecmd.py
- ewmutation.py
- ewrolemgr.py
- ewwep.py
- One Man's Junk: Only receive items from !barter and !barterall.
- !Legallimit is now self aware of the fact that there are no cops to enforce it.
- Juvies under level 19 are no longer invulnerable.
https://discord.com/channels/431237299137675295/431275470902788107/831348894298144828
https://discord.com/channels/431237299137675295/431275470902788107/831348930927132683
Edit: closed. In reviewing some conditionals I believe I edited them incorrectly. I'll have to review this code
> Remove Legallimit/Low Level Protection. Add mutation to barter for only items.

- ew/cmd.py
- ew/fish.py
- ew/move.py
- ew/static/cfg.py
- ew/static/smelting.py
related to issues #72 #74 #76  
did again due to another repository restructure
> Ghost barter fix. Ferro cost down. Skune fix. Landlocked Cooldown

- ew/utils/combat.py
> fixed raidboss movement

- client.py
- ew/cmd.py
- ew/static/cfg.py
- ew/static/weapons.py
- ew/utils/hunting.py
- ew/utils/leaderboard.py
- ew/utils/loop.py
- ew/wep.py
Fixed bug related to group spawning, and bug with leaderboards
Also updated mastery command and added postleaderboard command to force the leaderboard to update.
> Fixed a few bugs related to safari event

- ew/utils/combat.py
- Juveniles can now be targeted again by hunting enemies. Zug asked for this.
> ADDED JUVIE DEATH

- ew/static/cfg.py
- ew/static/items.py
- json/poi.json
- fixed a couple trophies
- fixed northern outskirts
> SAFARI FIX XVI

- ew/backend/item.py
- ew/food.py
- ew/hunting.py
- ew/juviecmd.py
- ew/static/cfg.py
- ew/static/items.py
- ew/utils/loop.py
- Fixed a bug with marriage where you couldn't equip your spouse
- Fixed a big-ass indentation error in ew/backend/item.py
- Fixed a few typos
- Safari bosses now spawn every seven-and-a-half minutes or so (from every two)
- Solved #71 : Mineshaft timer now only starts after message is sent
- Fixed safari boss announcements
- Safari bosses now spawn in Nuclear Beach instead of Downtown
- Rival Hunters more common
- Fixed bosses spawning at the wrong times
> SAFARI FIX XX

- ew/cmd.py
- ew/food.py
- ew/item.py
- ew/move.py
-fixed a custom furniture bug where the first purchase would change the furniture's item definition, making every future item bought have the same name
-changed custom furniture to include custom !inspect text in addition to names (!order [custom item] "custom name" "custom description")
-tping into sewers kills you
-sorting inventories by type now shows a little **==TYPE==** label before each new item type
-also fixed !goto apt trying to retire you even if you !stop
-!help mymutations always shows your mutations now
> changed custom furniture and tping into the sewers

- client.py
- ew/cmd/cmds/__init__.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/race/__init__.py
- ew/cmd/race/racecmds.py
- ew/static/cfg.py
- ew/utils/core.py
- Added cyborg and demon races
- Added !netrun and !strikedeal
- Moved some of the general race flavor text into a dictionary in cfg to remove some big if else in the !data and !setrace functions
- added DEBUG_OPTIONS to utils to be able to live toggle debug features for testing
> Cyborg and Demon races

- ew/cmd/cmds/cmdcmds.py
- ew/cmd/race/racecmds.py
- ew/utils/cmd.py
- !data @ others works again
- certain other race commands have been fixed and had some grammar issues fixed
> Fixed some race stuff so you can data other people again 

- ew/cmd/race/racecmds.py
Also Grammar Fixes, Spoiler Alert!!!!!!!! What the HECK Connor, don't block me next time 😭😭😭😭😭😭😭😭😭😭😭😭😭
> Adds more flavor text to Demons and Cyborgs

- ew/cmd/cmds/cmdcmds.py
Fixed a couple of accidental bugs with my last PR
> Quick Fixes

- ew/static/items.py
I named Ferroslimeoid Otamatone "FERROIDslimeoid otamatone".
:redman:
> Ferroid patch

- ew/cmd/slimeoid/slimeoidcmds.py
User-side Patch Notes:
- Fixed slimeoid trainer challenging
> Fixed slimeoid trainer challenging

- ew/cmd/item/itemcmds.py
- ew/utils/item.py
The booster boxes are bugged af, after you pull a slimexodia piece, the rest of the pieces will be slimexodia. PLZ PULL THIS BEFORE SOMEONE EXPLOITS IT
> Booster Box fix Dear GOD pull this before it's exploited

- ew/backend/item.py
whoops. This should fix ordering food, and hopefully a bunch of the other issues
> Fixed issue where expiry time was not set in cache for new items

- ew/backend/item.py
- ew/cmd/apt/aptcmds.py
- ew/utils/slimeoid.py
The cache shouldnt be throwing errors anymore. fingers crossed
> fixed various bugs. some related to cache and some pre-existing

- ew/cmd/cmds/cmdcmds.py
- ew/cmd/slimeoid/slimeoidcmds.py
- ew/cmd/slimeoid/slimeoidutils.py
- ew/utils/combat.py
- ew/utils/hunting.py
This fixes all the current bugs with Slimeoids and Negaslimeoids (if merged with Frog's current PR)
- Makes Slimeoid Bets go to the actual winner!
- Makes killing Slimeoid Trainers actually, like, reward you
- Makes Slimeoid Trainers reward you Slimecoin
- Makes Negaslimeoids battleable, just like old times.
- Makes Champion Slimeoid Trainers spawn with bigger, better slimeoids.
- Makes level-up text use your gender, instead of "slimeboi" 😌
> Slimeoid Bug Fix 2.0

- ew/static/fish.py
- ew/utils/leaderboard.py
- ew/utils/loop.py
Moves market_data.persist() from ABOVE update_stocks to BELOW update_stocks, which seemingly fixes the stock market with no issues. There MIGHT be issues, but 3 hours of testing didn't show any.
Also adds a period to 2 fish descriptions, 'cuz they're missing them 😔
> Stock Market Fix?!?!?!🤯

- ew/backend/item.py
- ew/cmd/fish/fishutils.py
- ew/cmd/item/itemcmds.py
- ew/cmd/smelting/smeltingcmds.py
- ew/utils/loop.py
- ew/utils/market.py
redid the naming function again. I couldnt break it but I'm tired and incapable of the intensive testing that is pushing to live. Seemed to work with createall and extractsoul.
> Please let this work

- ew/cmd/slimeoid/slimeoid_creation.py
- ew/cmd/slimeoid/slimeoidcmds.py
Fixed negative stats
You can now dissolve a forming slimeoid, added this judging from its flavour text
> slimeoid lab fixes

- ew/cmd/food/foodcmds.py
Fixes !menu, making prices show up correctly (I'm like 99.99% sure. May have tested this wrong, I've literally never capped the map once in my life).
> Party Fix II - Juvie Moment DX

- client.py
- ew/backend/user.py
- ew/cmd/wep/wepcmds.py
- ew/cmd/wep/weputils.py
- ew/static/cfg.py
- ew/static/status.py
- ew/static/weapons.py
- ew/utils/combat.py
- ew/utils/frontend.py
- You may now attack without a weapon
- Molotovs, Dclaw, Grenades, and Napalm Snot work again
- Napalm snot now does half of the final attack damage
- Backfire damage is now formatted
- weapon explosions dont error out when there isnt a kingpin anymore
- Attacking should generally work faster
- A lot of weird, small, potential/active bugs were fixed
- Theres probably some new bugs so dm me if somethings weird with combat
> New Attack Function

- ew/utils/apt.py
I don't know how this could be exploited but I sure am glad it wasn't because I'm willing to bet it could've been
> Fixed a bug where squatters could be sent to PoIs that didnt exist

- ew/static/cfg.py
- ew/static/poi.py
- ew/utils/dungeons.py
!Kills the White Line, stashing it for next year. Bye bye, White Line!
Also adds "uw" to the Underworld's aliases, changes the version number to reflect Slimernalia, and fixes a refactor error with the old tutorial code.
> !Killing the White Line 😢😔

- ew/cmd/casino/casinocmds.py
- ew/cmd/casino/casinoutils.py
Gamblerino Fixerino
Patch Notes:
- Removed Ghost Gambling
- All & Half Gambling is now fixed
> Big Gambling Fixerino

- ew/cmd/wep/wepcmds.py
- ew/utils/core.py
At some point sigil code just got deleted so it wasnt even there to be toggled with slimernalia. added the creation code back as if slimernalia active create sigil, else create scalp.
Also realized get_most_festive was still searching every item in existence for every player to find their sigils so I gave it the same treatment as the leaderboard function.
> Added Sigillarias Back and Optimized get_most_festive

- ew/cmd/item/itemutils.py
- ew/cmd/market/marketcmds.py
- ew/cmd/wep/wepcmds.py
- setup.sql
3 incredibly minor fixes that were brought up in nurses-office.
- Giving fish at the museum now gives the correct amount of slime instead of a flat 100,000 🐠
- Scalps can now do this really quirky thing and drop 🦲
- Weapon kills now accurately track in weapon collections 🗡️
Also fixes a comma in setup
> Incredibly Minor Fixes 🥳🎈

- ew/cmd/apt/aptutils.py
- ew/cmd/wep/weputils.py
- ew/static/cfg.py
Patch Notes:
- Apartment keys work again
- Added hunger penalty to buffering & fixed a kill error
- Reduced the timer for offline paralysis down to 5 seconds. We'll feel out the difference and makes changes as we go.
> Misc. Fixes

- ew/cmd/item/itemcmds.py
- ew/cmd/smelting/smeltingcmds.py
- ew/cmd/spooky/spookycmds.py
- ew/cmd/wep/wepcmds.py
- ew/static/cfg.py
Some more incredibly minor fixes 😌
- Fixes duels so that they work I'm pretty sure. Was a missing thing in cfg.py.
- Turns id_owner into a string if it's ever an integer, so that inspecting rotten fish works.
- Fixes WCIM not working with aliases, as well as adding flavor text to unsmeltable cosmetics so that they don't send an empty message.
also a spelling fix and a fix to a comment in the duel command
> Incredibly minor fixes again 🥳

- ew/cmd/debug_dummy/debugutils.py
- ew/cmd/debugr_dummy/debugrelics_dummy.py
- ew/cmd/market/marketcmds.py
- ew/cmd/spooky/spookycmds.py
- ew/cmd/wep/wepcmds.py
- ew/static/rstatic_dummy.py
Fixed debug imports and dummy files to allow the bot to run without secret files
> QOL for Non-BP Devs

- ew/backend/core.py
- ew/cmd/debug_dummy/debugutils.py
- ew/cmd/debugr_dummy/debugrelics_dummy.py
- ew/cmd/market/marketcmds.py
- ew/cmd/spooky/spookycmds.py
- ew/cmd/wep/wepcmds.py
- ew/static/cfg.py
- ew/static/rstatic_dummy.py
Fairly technical, Stotle has the rundown. To simplify, the cache builds lists of items that share a value for the configured properties, currently limited to owner id, to effectively cache inventories, and item type, so type searches are much faster.
> Cache Property Indexing

- ew/static/cfg.py
- ew/utils/market.py
Bazaar now checks if there are any relics to add before trying to add one
> Fixed Time Stopping

- ew/utils/combat.py
we all know what's happening here. whoops
> lazy fix for a stupid bug

- ew/static/cfg.py
Fixed some notorious gramer and speling mistakes fond within !crime messages.
> Improved !crime grammar

- ew/cmd/cmds/__init__.py
- ew/cmd/cmds/cmdcmds.py
- ew/static/cfg.py
- ew/static/smelting.py
- ew/static/status.py
- ew/static/weapons.py
Much much much much MUCH thanks to zug for guiding me through this process, EW code scares me
Adds a smeltable variable-damage skateboard weapon (2 nailbats, 1 leather, 1 ironingot, and 1 rollerblades) that you can also do !tricks with
First actual real update so yay me :)
> crooking off my great grandmas coffin

- ew/cmd/cmds/__init__.py
- ew/cmd/cmds/cmdcmds.py
- ew/static/cfg.py
changed trick to stunt and added skate as an alias (because oops lmao)
> tony hawk permadeath

- ew/cmd/apt/aptcmds.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/slimeoid/slimeoid_creation.py
- ew/cmd/slimeoid/slimeoidcmds.py
Fixes the props for Clout Goggles. My brain is so big 😩
> Clout Goggles Fix 🥺👉👈

- ew/cmd/cmds/cmdcmds.py
- ew/cmd/juviecmd/juviecmds.py
- ew/cmd/race/racecmds.py
- ew/cmd/slimeoid/slimeoidcmds.py
- ew/cmd/slimetwitter/slimetwittercmds.py
What the title says. Make sure to merge with MAJYKKS' thing or else !setrace and !enlist killer won't work
> Skateboard fix, floorslime bugfix, makes clowns rowdy-exclusive

- ew/cmd/cmds/cmdcmds.py
- ew/cmd/market/marketcmds.py
> Fishing event !turnin and !bid fix

- ew/cmd/cmds/cmdcmds.py
- ew/static/cfg.py
- ew/static/mutations.py
Comments out Gay - the auto-remove feature doesn't work in practice so I'll fix that in a future patch.
> Comments out Gay

- ew/static/cfg.py
- ew/static/cosmetics.py
- ew/static/food.py
- ew/static/items.py
- ew/static/poi.py
- ew/static/smelting.py
it's just fixes haha, no need to look into it haha.
> Cosmiture Wave 1.1

- ew/cmd/race/racecmds.py
> rattle expansion patch

- ew/backend/goonscapestats.py
- ew/backend/questrecords.py
- ew/cmd/cmds/__init__.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/farm/farmcmds.py
- ew/cmd/fish/fishutils.py
- ew/cmd/juviecmd/juviecmds.py
- ew/static/cfg.py
- ew/utils/combat.py
- ew/utils/frontend.py
- setup.sql
RuneScape style stat leveling for the following skills -Mining
-Fishing
-Farming
-Eating food
more to come and hopefully some npc interactions when those are added
> MCMMO aka OLD SCHOOL GOONSCAPE

- ew/cmd/item/itemcmds.py
- ew/cmd/smelting/smeltingcmds.py
- ew/static/cosmetics.py
- ew/static/items.py
- ew/static/smelting.py
fixes wcim issues hopefully.
Wcim for non cosmetics was broken due to an indention error it seems.
Wcim for cosmetics would say that it can smelt profollean cosmetics through random smelting -it couldn't and now shouldn't pretend it can.
> yeah, random recipes sure r annoying.

- client.py
- ew/cmd/cosmeticitem/cosmeticcmds.py
- ew/cmd/debug_dummy/debugcmds.py
- ew/cmd/debugr_dummy/debugrelics_dummy.py
- ew/cmd/wep/wepcmds.py
- ew/utils/rutils_dummy.py
I made the dummy files work so now your average joe blow pulling the codebase will have it work properly without having to patch in little changes every time they want to start up the bot
> Dummy files now work

- ew/cmd/fish/fishutils.py
- ew/cmd/move/movecmds.py
- ew/cmd/wep/wepcmds.py
- ew/static/poi.py
- ew/static/weapons.py
if I find a good fix for the issue with !survey in the saloon and the square, I'll add that to this branch as well
> fixed a bug with annoint, survey, vendors, and the lint test

- client.py
- ew/cmd/apt/aptcmds.py
- ew/cmd/cmds/__init__.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/move/movecmds.py
- ew/cmd/move/moveutils.py
- ew/cmd/spooky/spookycmds.py
- ew/cmd/transport/transportcmds.py
- ew/cmd/wep/weputils.py
- ew/static/cfg.py
- ew/static/poi.py
- ew/static/weather.py
- ew/utils/loop.py
- ew/utils/transport.py
- ew/utils/weather.py
Turns on RP City as well as some smaller Double Halloween buffs.
Also adds !forecast, so. Uh. That too.
> Quick Octoberdate (Not the Big One yet)

- ew/static/food.py
Killer Kandy Kode for double Halloween
> Killer Kandy for Double Haloween 

- ew/static/community_cfg.py
stops kill feed from saying people attacked and kill themselves
> kill feed typo fixing

- ew/cmd/fish/fishutils.py
- ew/cmd/move/movecmds.py
- ew/cmd/wep/weputils.py
- ew/static/cfg.py
- ew/static/fish.py
- ew/static/hunting.py
- ew/static/poi.py
- ew/utils/hunting.py
Fixes a fishing bug with ferroslimeoids, a bug with manual_spawn and pre_chosen_rarity, and then !crush and movement in raid dens (again). Adds sniffing raid den entrances and also defense_up_enemies.
> Splatoween (DH 2022 fix 3)

- ew/cmd/casino/casinoutils.py
- ew/cmd/cmds/cmdcmds.py
- ew/static/cfg.py
- ew/utils/combat.py
- ew/utils/core.py
- ew/utils/frontend.py
- ew/utils/leaderboard.py
- ew/utils/loop.py
- ew/utils/market.py
- ew/utils/rolemgr.py
- ew/utils/weather.py
- Fixed slimernalia kingpin election
- Enabled mobile slime gambling
- Fixed the main time loop so it should get stuck less often
- Fixed enemy spawning
- !yoslimernalia now awards a little festivity
- Sigillaria now longer award festivity from your inventories, instead more festivity is awarded to kills
- Fixed the festivity leaderboard
> Another set of Slimernalia Fixes & Changes

- client.py
- ew/static/community_cfg.py
- ew/static/cosmetics.py
- ew/utils/core.py
more slimernalia fixes, including:
- fixed kingpin election (again)
- diner now sells cigs
- join message should work now
- fixed a bug with katanas and kill feeds
> MORE BUG FIX

- ew/static/cfg.py
- ew/static/items.py
- ew/utils/core.py
-Slimernalia Kingpin should now be chosen by the HIGHEST FESTIVITY. AS INTENDED. INSHALLAH? (wait until it still doesn't work and i send myself down a flight of stairs)
-Populated gift ribbons to be obtained through mining/farming/fishing, something I overlooked and slipped out of my todo list on arrival
-Rebalanced gift ribbon drops from the slimernalia mobs to account for this
> Please just fucking be fixed already

- ew/cmd/cmds/cmdsutils.py
- ew/cmd/item/itemcmds.py
- ew/cmd/juviecmd/juviecmds.py
- ew/static/cfg.py
- ew/static/fish.py
- ew/static/items.py
- ew/utils/core.py
-Sledgemining will remain after slimernalia
*If you wield a sledgehammer *and* are enlisted, you still get double slimegain like you are wielding a pickaxe
**no, you aren't getting juviepick mining with the sledgehammer, but you can still sledge mine with the normal rates as a juvenile
-Slimeringcan and shovel QoL also are now permanent stayins.
-Festivitystage set to 6.
Future reworkings of slimernalia additions so that you won't have to deal with festivity stages next year will be made after S4A2.
> Festivity Stage 6

- ew/static/cfg.py
> no more fortnite!

- ew/cmd/cmds/cmdcmds.py
- ew/utils/combat.py
- ew/utils/weather.py
These not being done properly has bugged fishing for years, probably negatively-affected the game in other ways. spooky 😱
> 🎲Quick fix for seeding

- ew/cmd/wep/wepcmds.py
- ew/cmd/wep/weputils.py
- ew/utils/combat.py
- Enemies no longer take/deal improper damage compared to PvP
> Fixed Damage Bug

- client.py
- ew/backend/core.py
- ew/backend/user.py
- ew/cmd/kingpin/kingpincmds.py
- ew/utils/combat.py
- ew/utils/core.py
- ew/utils/frontend.py
- id_user now treated like an int coming from the database
- execute_sql_query now has a fetchone optional kwarg
- EwUserBase now INSERTS new rows and UPDATES existing rows, instead of always REPLACEing
Didn't test much besides that a few clock ticks didn't randomly delete my data or fail to kick a bunch of people (since they aren't in my server, even though their id_servers were all changed to match the test server) for missing rent they totally had. Other things may have (but as far as I know SHOULDN'T have) been broken but I didn't have time to go test all the basic features.
> users.id_user is an int

- .github/workflows/.python-package-conda.yml
- ew_env.yml
- requirements.txt
- Github tests now work again
- Updated the yaml file to some modern files (the bot actually tests properly)
> Housekeeping Update

- ew/static/community_cfg.py
more kill feed part 1
goal is 4 killtexts per weapon
feel free to edit/add more
> more kill feed part 1

- ew/cmd/item/itemcmds.py
- ew/cmd/kingpin/kingpincmds.py
Makes "!create" able to specify freshness. Also lists item ID when creating. Makes item_use work with cosmetics, for fun.
> 🎉 !create and item_use() changes 🥳

- ew/backend/goonscapestats.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/cosmeticitem/cosmeticcmds.py
- ew/cmd/item/itemcmds.py
Also turns the freshness of skill capes from 1 to 0.
> Allow adornment of 0 space items when you have negative fashion slots

- ew/cmd/cmds/cmdcmds.py
- ew/cmd/cosmeticitem/cosmeticcmds.py
- ew/static/cosmetics.py
- ew/utils/cmd.py
-Fixes 1 faulty cosmetic
-Skill capes (can hopefully) be adorned with no spare space now for real this time 
-Un-vomits the spacing problems on !data
> the T stands for rushed commits

- ew/cmd/cmds/cmdcmds.py
- ew/cmd/juviecmd/juviecmdutils.py
- ew/static/cfg.py
- ew/static/mutations.py
You don't get any penalty for hitting a mine in the beginning of minesweeper now.
+ Adds Gay (just like last year) and minecollapse worldevent changes to reduce ratelimit.
> Reimplementing First Cell Immunity in Minesweeper + Gay mutation

- ew/cmd/juviecmd/juviecmds.py
- ew/cmd/race/racecmds.py
Sowwy TwT I did that code directly on GitHub cus I'm dumb. Anyway: 
- I get OCD when I see non thought of possibilities within a piece of code, so I added a response for when people put !talk without anything else, and for when someone @ s themselves with that command.
- I extended !requestpetting, so the petting between two critters has different flavor text. It might be lowkey cringe, but I saw my cats doing that and I HAD to do this.
> Sorry for not debugging before, Stotle QwQ. Small addition to !talk and !requestpetting, not much else for now.

- ew/cmd/race/racecmds.py
So yeah, fixed what I fucked up last time + added rejection for race commands that involve @ ing people, cus the only one that had that was !strikedeal. I've changed those commands as little as I could cus I'm not optimizing that shit. It's not like EW code is known to be optimal anyway.
> Petting fixed, rejection for !racecommand @self

- ew/cmd/wep/wepcmds.py
- ew/static/weapons.py
Sorry for the long wait, I was working on a personal project.
> Fixed !kill not working
