aristotlepenguin/endless-war

- client.py
- ewapt.py
- ewcfg.py
- ewcmd.py
- ewfarm.py
- ewfish.py
- ewhunting.py
- ewjuviecmd.py
- ewmutation.py
- ewrolemgr.py
- ewwep.py
- json/poi.json
- Juveniles can't be killed for just being in districts, they need to be flagged.
List of actions that cause you to be flagged and their timers:
Mining -> 5 minutes
Scavenging -> 10 minutes
Knocking -> 1 minutes
Reaping -> 30 minutes
Reeling fish -> 10 minutes
Grafting or chemo -> 10 minutes
- Because of this, !checkflag can be used again.
Unrelated to juvies - Being in Juvies Row subzones no longer gives you the Wanted role.
Note: juvies get the wanted role even in gang bases and JR. This is just so they can know they're flagged.
> flags for juvies

- client.py
- ewcfg.py
- ewcmd.py
Now players can do !mastery to check all of their masteries (weapons and tools) in one easy command. Instead of having to !data yourself while switching between different weapons and tools to check your skill levels, you can just check all of them with one simple command.
I left out the ability for players to !mastery check others on purpose to avoid any possible easy surveillance of other people's masteries.
> QoL: Check mastery command

- ewutils.py
Unsure why live version was blocking !stows/!discards for some districts, assumed live DB has user table entries for chests (based on the chest->dt incident) so a check was added to ewutils.is_player_inventory to ensure user is a member in target server. Can't imagine any other cause.
> Hopefully fixed bug where chests are counted as player inventories

- ew/faction.py
Basically it didn't work because I used the variable vouchee_data before it being defined, it should be fixed now.
Now with this update, vouching can only be done if the two guys are in the same place. I feel like this will make vouching better as a whole, but I understand we need to temporarily test it to see how the community uses this feature though.
Hopefully, it will make vouching work more as it was intended to in the beginning.
> Fixed vouching (sorry for breaking it uwu)

- client.py
- ew/backend/core.py
- ew/backend/item.py
- ew/backend/player.py
- ew/backend/user.py
- ew/cmd/apt/aptcmds.py
- ew/cmd/cmds/__init__.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/cosmeticitem/cosmeticcmds.py
- ew/cmd/faction/factioncmds.py
- ew/cmd/item/__init__.py
- ew/cmd/item/itemcmds.py
- ew/cmd/item/itemutils.py
- ew/cmd/juviecmd/juviecmds.py
- ew/cmd/move/movecmds.py
- ew/cmd/move/moveutils.py
- ew/cmd/wep/wepcmds.py
- ew/static/cfg.py
- ew/utils/combat.py
- ew/utils/core.py
- ew/utils/cosmeticitem.py
- ew/utils/item.py
- ew/utils/leaderboard.py
- ew/utils/prank.py
Items are now retrieved from and saved to a cache if available
- Added !createall <number of copies> <target mention> for admin use to create a variable number of all in game items
- Added !togglecache <0 or 1> <object type, ex: EwItem> to disable the cache if there are any issues, and reload the cache if something is directly changed in the database by hand
- Only one chest/inventory print can be active in any particular channel
- Chests can now be viewed from DMs, in case someone is trolling and spamming a full print when a user just needs to search
- Rowdy Roughchest and other massive inventories will no longer freeze the entire bot when used.
- Items now generate their name themselves instead of relying on the inventory function to figure it out
> Adding cache

- ew/cmd/cmds/__init__.py
- ew/cmd/cmds/cmdcmds.py
- ew/static/cfg.py
!verifycache will get all items in the server it is called in through the same inventory function as find_item, and try flattenTokenListToString with the item's name, and on exception will log the item's id and cached data.
> Added !verifycache for admin use

- ew/cmd/casino/casinocmds.py
- ew/cmd/casino/casinoutils.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/item/itemcmds.py
- ew/cmd/mutation/mutationcmds.py
- ew/cmd/wep/wepcmds.py
- ew/static/cfg.py
- ew/utils/combat.py
- ew/utils/core.py
- ew/utils/frontend.py
Patch Notes:
- Phoebus has had enough of this !slimecraps 0 bullshit, and has completely reworked the way festivity is gained! Gift giving, killing, eating handmade foods and slime gambling are great ways of getting festivity!
- When failing to !eat a rotten food, you'll now be told what food you failed to eat
- "Optimised" festivity code
Developer Notes:
- This update should be used in conjunction with a reset on festivity and festivity_from_slimecoin for all users
- Refactored gambling code
- Slimecoin gambling no longer gives festivity
- Slime gambling now calculates festivity using a / 1000 linear function instead of some heavily broken exponentials
- Slime bets above 1,000,000 reward a 10,000th of the bet as festivity as a bonus whether or not you win the bet
- Eating handmade …
> Slimernalia Updates

- client.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/item/itemcmds.py
Changes !wrap so that items can only be !wrapped once ever. Regifting is BANNED.
Makes it so that you are unable to !give yourself items.
Makes it so that !unwrapping gifts you yourself made gives you 0 festivity.
Makes !yoslimernalia function like !awoo - typing any length variation of !yoslimernalia or using !yoslimernalia in the middle of a message will still trigger !yoslimernalia (request from Luca).
Uhhh in terms of the code:
!Wrapping an item now gives it the "gifted" prop once !unwrapped. Any items with the "gifted" prop are unable to be !wrapped.
> !Give festivity exploit patch 💃🎁🧍(also !yoslimernalia thing)

- ew/backend/item.py
- ew/utils/leaderboard.py
- bknd_item.get_freshness now accepts a kwarg "adorned_id_list" as a list of adorned cosmetic ids
- utils.leaderboard now passes its initially collected group of adorned cosmetics to get_freshness instead of calculating each candidate's freshness as they are checked, saving a lot of inventory calls
averaged 97% reduction in generation time for the freshness board, results on server hardware may vary though
> Freshness Leaderboard Speedup

- ew/backend/core.py
- ew/utils/combat.py
- ew/utils/item.py
- Added bulk_set_entry to have allow the cache to be fed a list of items, and update as simultaneously as possible, though iterative set_entrys were barely slower so this was (kinda) pointless
- Changed the relic dropping on death function to get ids from the cache rather than querying the sql
- Changed .die to use the new bulk cache update function, down from .01 seconds for 525 items to .008. Basically just making sure the function works right before applying it to multistow
- fixed an apparent bug in find_entries where the return clause was indented too far to run if fed a list of ids as opposed to criteria, and also fixed the lack of copying of data to be returned in that case
> Cache multi-update

- ew/static/food.py
Fixes the krakacola shortened alias because it used the same alias as drfucker (how did this never go noticed?)
Literally just changes two letters, not very exciting
> Krakacola alias fix

- ew/utils/combat.py
Updated certain variables during die() to update to a dead player's state after they're used, rather than before. Should fix weapons teleporting.
> Fixes weapons teleporting on death

- ew/static/cfg.py
- ew/utils/core.py
- ew/utils/leaderboard.py
- ew/utils/rolemgr.py
I fixed the dumb issue thing THAT WASNT MY FAULT! Turns out the cop killer and rowdy fucker roles are stored in the faction_roles list but weren't in the code that determined a user's proper faction roles, so it'd remove them and only add back the flat "kingpin" role, not the proper faction-specific ones.
**NOW**:
- Kingpin lifestates are tied to the "Kingpin" role. If you give it to a lowly gangster or juvie, they'll digivolve into their respective faction's kingpin based on their faction.
- If you remove the "Kingpin" role from a kingpin, they will degrade into a gangster if they have a faction, and a juvenile if they don't.
- Kingpin roles are fixed, and should not degrade
- Do NOT give the kingpin role to someone OR the rowdy fucker / cop killer role. DO NOT DO THAT.
> fixed kp issue (better than zugs)

- client.py
- ew/backend/status.py
- ew/cmd/item/itemcmds.py
- ew/cmd/item/itemutils.py
- ew/cmd/move/movecmds.py
- ew/cmd/wep/wepcmds.py
- ew/cmd/wep/weputils.py
- ew/model/poi.py
- ew/model/weapon.py
- ew/static/cfg.py
- ew/static/poi.py
- ew/static/status.py
- ew/static/weapons.py
- ew/utils/core.py
- ew/utils/loop.py
- ew/utils/move.py
- Removed captcha from molotov, for a price :}
- Burn should be much more consistent in damage dealt, relative to what was applied
- fixed a bug where weapon explosions and AOE burn would only grab player objects from the database for names, causing the creation of a player table entry with no name or avatar logged, and adding the flavortext for a bystander being hit, but not including the name.
- For weapon explosions, this was implemented with fetch_member, so if someone has the new player bug or is failing to cap for no apparent reason, throw a grenade at an enemy gangster (relative to the broken player and the thrower) in the same district. Probably won't work but who knows
- Also included isSplit removal from my master branch
If I did this poorly, both movement and murder could be …
> Reimplemented Backfiring

- client.py
- ew/backend/item.py
- ew/cmd/apt/aptcmds.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/item/itemcmds.py
- ew/cmd/move/movecmds.py
- ew/cmd/mutation/mutationcmds.py
- ew/cmd/slimeoid/slimeoid_creation.py
- ew/cmd/slimeoid/slimeoidutils.py
- ew/cmd/smelting/smeltingcmds.py
- ew/utils/apt.py
- ew/utils/combat.py
Apartment functions should no longer initialize EwItem(id_item=0) when apartments have no keys. Not urgent, but the logs get cluttered by the failure to find an item with the matching id.
Also removed some "print()" statements left in after testing by other contributors.
> Log Cleanup and Minor Bug Fixing

- .gitignore
- ew/backend/market.py
- ew/cmd/wep/wepcmds.py
- ew/cmd/wep/weputils.py
- ew/utils/loop.py
- ew/utils/market.py
- Made all stock updates within a tick have the same timestamp, using same variable as the market's time_lasttick
- Seeing as EwStock only every needs the latest, or 2 latest, entries for a stock, implemented a default limit of 1 with a switch to set the limit to 2
!menu was blocking heartbeats because it had to query for every. single. row. of every. single. stock. when used in the food court, even though all but the latest would be tossed out by the end of EwStock.__init__(). That was legitimately stupid. The query now includes the LIMIT sql keyword
> Calling EwStock() should no longer freeze the bot

- ew/backend/item.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/faction/factioncmds.py
fix #1: my preventing spam snag/stow code was bad. It now accounts for named weapons being mixed into a multisnag and is hopefully generally more hardy. I added a try: except: so that if in the future an error gets thrown for whatever new reasons, the chests dont also become inaccessible because of it.
When u get pushed off the cliffs, cosmetic item props werent fixed, so when cosmetics were reeled up they'd be automatically adorned because adorned=True. The same was true of stuff that had slimeoid=True, but i decided to make slimeoids not lose their cosmetics when the *player* jumps off the cliff rather than drop them and set that to false. Some slimeoids can fly and if they jumped anyway, they should probably die and turn to a heart (but thisd be such a killjoy 0_0) so i dont think it …
> bug fixes to snag and cliff stuff

- ew/backend/item.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/cmds/cmdsutils.py
- ew/cmd/fish/fishcmds.py
- ew/cmd/juviecmd/juviecmdutils.py
- ew/cmd/move/movecmds.py
- ew/cmd/wep/weputils.py
- ew/static/items.py
- ew/static/weapons.py
- ew/utils/core.py
- ew/utils/frontend.py
- ew/utils/rolemgr.py
- create mining events without a weapon works now
- !commands location will assume your current location when no 3rd token is given
- !commands location may be used with whitespace in the poi target, without the need for quotations
- !kill in a safezone without targeting an enemy no longer Errors
- !brandish juvierangs response properly defined
- !barter and !barterall changed to use item prices for value comparison, instead of context, to prevent int/str comparisons
- Several instances of print() removed, or switched to logMsg and given context
> Frog feeding

- ew/cmd/cmds/cmdcmds.py
- ew/cmd/wep/wepcmds.py
- ew/cmd/wep/weputils.py
- ew/model/status.py
- ew/static/status.py
- ew/utils/combat.py
- Annoint now stops when telling the user they need a weapon
- Status effect attack mods now apply the same way as all other attack mods. Damage mods are multiplicative, hit and crit mods are additive. Fixes potential for negative attack multiplier.
> Annoint and Status Mod Fixes

- client.py
- ew/backend/user.py
- ew/cmd/apt/aptcmds.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/district/districtcmds.py
- ew/cmd/fish/fishutils.py
- ew/cmd/kingpin/kingpincmds.py
- ew/cmd/move/movecmds.py
- ew/cmd/move/moveutils.py
- ew/cmd/quadrants/quadrantcmds.py
- ew/cmd/quadrants/quadrantutils.py
- ew/cmd/raidboss/raidbosscmds.py
- ew/cmd/spooky/spookycmds.py
- ew/cmd/wep/wepcmds.py
- ew/cmd/wep/weputils.py
- ew/utils/apt.py
- ew/utils/combat.py
- ew/utils/core.py
- ew/utils/district.py
- ew/utils/frontend.py
- ew/utils/loop.py
- ew/utils/move.py
- ew/utils/prank.py
- ew/utils/weather.py
May be a bit overkill to have cast every possible assignment and add it as a limit fix, but this way it will be guaranteed to be a string no matter how it is input to the EwUser, which should give it consistent behavior. Without this commit, zug couldn't revive, with it Zug could. Not sure how exactly revival was being blocked, but this fixes it.
> fix revival of users with near-identical duplicate rows

- ew/cmd/wep/wepcmds.py
- ew/cmd/wep/weputils.py
- Weapon marriage now properly checks for ongoing marriages
- NPC 'hit' actions no longer trigger on miss (dojomaster no longer gives mastery unless successfully hit)
- Attacking enemies/NPCs no longer triggers explosive or burn AoE
> Exploit Fixes

- ew/backend/apt.py
- ew/backend/core.py
- ew/backend/goonscapestats.py
- ew/backend/item.py
- ew/cmd/apt/aptcmds.py
- ew/cmd/cmds/cmdcmds.py
- ew/cmd/item/itemcmds.py
- ew/cmd/kingpin/kingpincmds.py
- ew/static/weapons.py
- !editprops is not a terrifying mess-machine now
- Retire now checks if the user has an apartment (rent != 0)
- Default EwApartment location is now nowhere
- execute_sql_query now has an option to return the lastrowid for insert statements
- item_create given an option to overwrite defined soulbound status
- as a result of the last 2, goonscape stat capes will now be properly soulbound, and I can manually enter the sql to update old capes
- !aptupgrade and !addkey now actually stop users from spamming, as well as bitch at users who try to
> Bigger Fixes

- ew/cmd/cmds/cmdcmds.py
- ew/static/cfg.py
- A small mistake made it so ghosts and kingpins got the Slime's End Cliffs messages instead of the non poi ones outside there. Also added the chance to break your teeth while jumping, because why not.
- Now the faction specific commands (!dab, !thrash, !boo and !dance) have a response for people from other factions executing them. Why would they do that? Don't know, but I thought a small response from the bot acknowledging their stupidity was neat.
- !boo has changing emotes on the sides like !dab and !thrash.
> Small fix to !jump, faction commands and new emotes for !boo
